title: 笨方法实验室
description: 世上无难事，只怕笨方法
baseurl: ""
url: "https://hardwaylab.com"

theme: just-the-docs

# 导航与排序
just_the_docs:
  collections:
    course:
      name: 课程产品

# 排除文件
exclude:
  - README.md
  - Gemfile.lock
